#!/bin/sh
xset m 20/10 4

#gdnc
if ps ux | grep -v grep | grep 'gdnc' > /dev/null
then
    echo "gdnc running, everything is fine"
else
    echo "launching gdnc"
    /usr/local/bin/gdnc &
fi

#gnome-settings-daemon
if ps ux | grep -v grep | grep 'gnome-settings-daemon' > /dev/null
then 
    echo "gnome-settings-daemon running, everything is fine"
else
    echo "launching gnome-settings-daemon"
    /usr/local/libexec/gnome-settings-daemon &
fi

#compton
if ps ux | grep -v grep | grep 'compton'
then 
    echo "compton is running"
else
    compton &
fi

#GWorkspace
if ps ux | grep -v grep | grep 'GWorkspace'
then
    echo "GWorkspace is running"
else
    openapp GWorkspace &
fi

##AClock 
#if ps ux | grep -v grep | grep 'AClock'
#then
#    echo "AClock is running"
#else
#    openapp AClock &
#fi

#TopBar
if ps ux | grep -v grep | grep 'TopBar'
then 
    echo "TopBar is running"
else
    openapp TopBar.app &
fi


if ps ux | grep -v grep | grep 'conky'
then
    echo "conky is running"
else
    conky &
fi
