#!/bin/sh
xset m 20/10 4

#gdnc
if ps ux | grep -v grep | grep 'gdnc' > /dev/null
then
    echo "gdnc running, everything is fine"
else
    echo "launching gdnc"
    /usr/local/bin/gdnc &
fi

#gnome-settings-daemon
if ps ux | grep -v grep | grep 'gnome-settings-daemon' > /dev/null
then 
    echo "gnome-settings-daemon running, everything is fine"
else
    echo "launching gnome-settings-daemon"
    gnome-settings-daemon &
fi

#compton
if ps ux | grep -v grep | grep 'compton' > /dev/null
then 
    echo "compton is running"
else
    compton &
fi

#GWorkspace
if ps ux | grep -v grep | grep 'GWorkspace' > /dev/null
then
    echo "GWorkspace is running"
else
    openapp GWorkspace &
fi

#AClock 
if ps ux | grep -v grep | grep 'AClock' > /dev/null
then
    echo "AClock is running"
else
    openapp AClock &
fi

#GSPanel
if ps ux | grep -v grep | grep 'GSPanel' > /dev/null
then 
    echo "GSPanel is running"
else
    openapp GSPanel.app &
fi

#conky
if ps ux | grep -v grep | grep 'conky' > /dev/null
then
    echo "conky is running"
else
    conky &
fi
